#!/bin/bash

# linker

SCRIPTPATH="$( cd -- "$(dirname "$0")" >/dev/null 2>&1 ; pwd -P )"

echo "linker started"
sudo rm -rf /etc/nginx/custom-configs
sudo ln -sf $SCRIPTPATH/custom-configs /etc/nginx/custom-configs

sudo ln -sf $SCRIPTPATH/nginx.conf /etc/nginx/nginx.conf
sudo mkdir -p /etc/nginx/sites-available/
sudo mkdir -p /etc/nginx/sites-enabled/
sudo ln -sf $SCRIPTPATH/sites/*.conf /etc/nginx/sites-available/
sudo ln -sf $SCRIPTPATH/sites/*.conf /etc/nginx/sites-enabled/
sudo ln -sf $SCRIPTPATH/ssl /etc/nginx/
sudo mkdir -p /etc/nginx/modsec/
sudo mkdir -p /etc/nginx/modsec-crs/rules
sudo ln -sf $SCRIPTPATH/modsec/* /etc/nginx/modsec/
sudo ln -sf $SCRIPTPATH/modsec-crs/* /etc/nginx/modsec-crs/rules/
sudo ln -sf $SCRIPTPATH/html/* /var/www/html/


echo "linker finished"
